version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
    - "25565:25565"
    - "25575:25575"
    - "25575:25575/udp"
    env_file:
      - motd_override.env
      - docker.env
    environment:
      EULA: 'true'
      TZ: 'America/Chicago'
      DIFFICULTY: 'hard'
      OPS: 'nincodedo'
      OVERRIDE_SERVER_PROPERTIES: 'true'
      ICON: 'https://cdn.discordapp.com/icons/109466144993210368/a_63bcc148bca7700101d1fb6b9522d638.png'
      OVERRIDE_ICON: 'true'
      MEMORY: '2G'
      HARDCORE: 'true'
      FUNCTION_PERMISSION_LEVEL: '4'
      SPAWN_PROTECTION: '0'
      ENABLE_AUTOPAUSE: 'true'
      MAX_TICK_TIME: "-1"
      AUTOPAUSE_TIMEOUT_EST: '30'
      AUTOPAUSE_TIMEOUT_INIT: '30'
    volumes:
    - /mnt/e/Docker/minecraft:/data
    container_name: mc
    tty: true
    stdin_open: true
    labels:
      dev.nincodedo.gameservercommander.game: "Vanilla Minecraft"
  log-watcher:
    build: .
    image: nincodedo/mc-lame-log-watcher:latest
    container_name: log-watcher
    env_file:
      - docker.env
    environment:
      TZ: 'CST7CDT'
    volumes:
    - /mnt/e/Docker/minecraft:/mnt/e/Docker/minecraft
    - /var/run/docker.sock:/var/run/docker.sock
