version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java11
    ports:
    - "25565:25565"
    - "25575:25575"
    - "25575:25575/udp"
    env_file:
      - motd_override.env
      - docker.env
    environment:
      EULA: 'true'
      TZ: 'America/Chicago'
      DIFFICULTY: 'hard'
      OPS: 'nincodedo'
      OVERRIDE_SERVER_PROPERTIES: 'true'
      ICON: 'https://cdn.discordapp.com/icons/109466144993210368/a_63bcc148bca7700101d1fb6b9522d638.png'
      OVERRIDE_ICON: 'true'
      MEMORY: '2G'
      HARDCORE: 'true'
      FUNCTION_PERMISSION_LEVEL: '4'
      SPAWN_PROTECTION: '0'
      ENABLE_AUTOPAUSE: 'true'
      MAX_TICK_TIME: "-1"
      AUTOPAUSE_TIMEOUT_EST: '30'
      AUTOPAUSE_TIMEOUT_INIT: '120'
      TYPE: 'FORGE'
      FORGEVERSION: '36.1.0'
      VERSION: '1.16.5'
      REMOVE_OLD_MODS: 'true'
    volumes:
    - mc_server:/data
    - mc_mods:/mods
    - mc_mod_configs:/config
    container_name: mc
    tty: true
    stdin_open: true
    labels:
      dev.nincodedo.gameservercommander.game: "Vanilla Minecraft"
  log-watcher:
    build: .
    image: nincodedo/mc-lame-log-watcher:latest
    container_name: log-watcher
    env_file:
      - docker.env
    secrets:
      - discord_webhook
    environment:
      TZ: 'CST6CDT'
    volumes:
    - mc_server:/data
    - mc_mods:/mods
    - mc_mod_configs:/config
    - /var/run/docker.sock:/var/run/docker.sock
volumes:
  mc_server:
  mc_mods:
  mc_mod_configs:
secrets:
  discord_webhook:
    file: ./secrets/discord_webhook.txt
